#!/usr/bin/env python3
"""Wayfarers wiki helper.

  python3 scripts/wiki.py check      # find broken [[links]] and bad page headers
  python3 scripts/wiki.py generate   # rebuild Open Questions.md and Roadmap Progress.md
  python3 scripts/wiki.py all        # generate, then check

The generated pages are not committed (they're in .gitignore); the website build
(scripts/build-site.sh) creates them. Links to them always count as valid.

Standard library only; works with Python 3.9+.
"""
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content"
GENERATED = {"Open Questions.md", "Roadmap Progress.md"}
GENERATED_TITLES = {name[:-3].lower() for name in GENERATED}
STATUSES = ["stub", "draft", "needs-decision", "solid"]
CATEGORY_ORDER = ["Overview", "Roadmap", "Character Creation", "Lineages", "Classes", "Subclasses",
                  "Rules", "Magic", "Equipment", "Feats", "Running the Game", "Bestiary"]

WIKILINK = re.compile(r"(!?)\[\[([^\]|#\\\n]+)(?:#[^\]|\\\n]*)?(?:\\?\|[^\]\n]*)?\]\]")
TASK = re.compile(r"^(\s*(?:>\s*)*(?:[-*+]|\d+[.)])\s+)\[([ xX])\]")
FENCE = re.compile(r"^\s*(```|~~~)")


def read_pages():
    pages = []
    for path in sorted(CONTENT.rglob("*.md")):
        text = path.read_text(encoding="utf-8")
        meta, body = {}, text
        if text.startswith("---\n"):
            end = text.find("\n---", 4)
            if end != -1:
                raw = text[4:end]
                body = text[end + 4:].lstrip("\n")
                key = None
                for line in raw.splitlines():
                    m = re.match(r"^([A-Za-z_]+):\s*(.*)$", line)
                    if m:
                        key, val = m.group(1), m.group(2).strip().strip('"')
                        meta[key] = [] if val == "" else val
                    elif key and re.match(r"^\s+-\s+", line):
                        if not isinstance(meta.get(key), list):
                            meta[key] = []
                        meta[key].append(re.sub(r"^\s+-\s+", "", line).strip().strip('"'))
        pages.append({"path": path, "name": path.stem, "meta": meta, "body": body})
    return pages


def strip_code(body):
    out, fence = [], False
    for line in body.split("\n"):
        if FENCE.match(line):
            fence = not fence
            continue
        if not fence:
            out.append(re.sub(r"`[^`\n]*`", "", line))
    return "\n".join(out)


def link_index(pages):
    idx = {}
    for p in pages:
        names = [p["name"], p["meta"].get("title", "")]
        aliases = p["meta"].get("aliases", [])
        if isinstance(aliases, str):
            aliases = [aliases]
        for n in names + aliases:
            if n:
                idx[n.lower()] = p
    return idx


def rel_link(p):
    return p["name"] if p["path"].name != "index.md" else "index"


def questions(page):
    found, lines = [], strip_code(page["body"]).split("\n")
    for i, line in enumerate(lines):
        m = re.match(r"^>\s*\[!question\][-+]?\s*(.*)$", line, re.I)
        if not m:
            continue
        text = []
        for nxt in lines[i + 1:]:
            if not nxt.startswith(">"):
                break
            text.append(re.sub(r"^>\s?", "", nxt))
        found.append((m.group(1).strip() or "Design question", " ".join(text).strip()))
    return found


def tasks(page):
    done = total = 0
    fence = False
    for line in page["body"].split("\n"):
        if FENCE.match(line):
            fence = not fence
            continue
        if fence:
            continue
        m = TASK.match(line)
        if m:
            total += 1
            done += m.group(2) != " "
    return done, total


def plain(text, limit=240):
    text = WIKILINK.sub(lambda m: m.group(2), text)
    text = re.sub(r"[*_`]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text if len(text) <= limit else text[:limit].rsplit(" ", 1)[0] + "…"


def cat_key(p):
    c = p["meta"].get("category", "")
    return (CATEGORY_ORDER.index(c) if c in CATEGORY_ORDER else 99, c, p["name"])


def generate(pages):
    real = [p for p in pages if p["path"].name not in GENERATED]

    # Open Questions
    lines = ["---", 'title: "Open Questions"', "category: Overview", "status: solid", "tags:",
             "  - generated", "---", "",
             "*This page is generated by `scripts/wiki.py`. Don't edit it by hand; edit the pages it links to.*", "",
             "Every *Design question* box in the wiki, gathered in one place. Answer one by editing its page, "
             "replacing the box with the final rule, and adding a row to the [[Decision Log]].", ""]
    count = 0
    groups = [(p, questions(p)) for p in sorted(real, key=cat_key)]
    groups = [(p, q) for p, q in groups if q]
    last_cat = None
    for p, qs in groups:
        cat = p["meta"].get("category", "Other")
        if cat != last_cat:
            lines += [f"## {cat}", ""]
            last_cat = cat
        lines += [f"### [[{rel_link(p)}|{p['meta'].get('title', p['name'])}]]", ""]
        for title, text in qs:
            count += 1
            lines.append(f"- **{plain(title, 120)}**" + (f": {plain(text)}" if text else ""))
        lines.append("")
    if not count:
        lines += ["No open design questions.", ""]
    lines.insert(10, f"**{count} open questions across {len(groups)} pages.**\n")
    (CONTENT / "Open Questions.md").write_text("\n".join(lines), encoding="utf-8")

    # Roadmap Progress
    road = [p for p in real if p["meta"].get("category") == "Roadmap"]
    rows = []
    for p in sorted(road, key=lambda p: p["name"]):
        d, t = tasks(p)
        if t:
            rows.append((p, d, t))
    td, tt = sum(r[1] for r in rows), sum(r[2] for r in rows)

    def bar(d, t, width=20):
        n = round(width * d / t) if t else 0
        return "█" * n + "░" * (width - n)

    lines = ["---", 'title: "Roadmap Progress"', "category: Roadmap", "status: solid", "tags:",
             "  - generated", "---", "",
             "*This page is generated by `scripts/wiki.py`. Tick tasks off on the phase pages.*", "",
             f"**{td} of {tt} roadmap tasks done ({round(100 * td / tt) if tt else 0}%).** See [[Roadmap]] for the plan.", "",
             "| Page | Progress | Done |", "|---|---|---|"]
    for p, d, t in rows:
        lines.append(f"| [[{p['name']}]] | `{bar(d, t)}` | {d} / {t} |")
    lines.append("")
    status_counts = {s: 0 for s in STATUSES}
    for p in real:
        s = p["meta"].get("status", "stub")
        status_counts[s if s in status_counts else "stub"] += 1
    lines += ["## Page status across the wiki", "", "| Status | Pages |", "|---|---|"]
    for s in STATUSES:
        lines.append(f"| {s} | {status_counts[s]} |")
    lines.append("")
    (CONTENT / "Roadmap" / "Roadmap Progress.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"generated: {count} open questions, {td}/{tt} roadmap tasks")


def check(pages):
    idx = link_index(pages)
    problems = 0
    names = {}
    for p in pages:
        names.setdefault(p["name"].lower(), []).append(p["path"])
        rel = p["path"].relative_to(ROOT)
        if p["path"].name in GENERATED:
            continue
        m = p["meta"]
        if not m:
            print(f"{rel}: missing frontmatter header"); problems += 1; continue
        for key in ("title", "category", "status"):
            if not m.get(key):
                print(f"{rel}: missing '{key}' in header"); problems += 1
        st = m.get("status")
        if st and st not in STATUSES:
            print(f"{rel}: status '{st}' should be one of {', '.join(STATUSES)}"); problems += 1
        tags = m.get("tags", [])
        if isinstance(tags, str):
            tags = [tags]
        if st and f"status/{st}" not in tags:
            print(f"{rel}: add the tag 'status/{st}' to match 'status: {st}'"); problems += 1
        if len([t for t in tags if t.startswith("status/")]) > 1:
            print(f"{rel}: more than one status/ tag"); problems += 1
        for mm in WIKILINK.finditer(strip_code(p["body"])):
            target = mm.group(2).strip()
            if target.lower() in GENERATED_TITLES:
                continue
            if target.lower() not in idx and not (ROOT / "content" / target).exists():
                print(f"{rel}: link to missing page [[{target}]]"); problems += 1
    for n, paths in names.items():
        if len(paths) > 1 and n != "index":
            print(f"duplicate page name '{n}': " + ", ".join(str(x.relative_to(ROOT)) for x in paths)); problems += 1
    print(f"checked {len(pages)} pages: {problems} problem(s)")
    return problems


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "all"
    if cmd in ("generate", "all"):
        generate(read_pages())
    if cmd in ("check", "all"):
        sys.exit(1 if check(read_pages()) else 0)
    if cmd not in ("generate", "check", "all"):
        print(__doc__); sys.exit(2)


if __name__ == "__main__":
    main()
